
export const textInGroupingMenu = {
	records: 'רשומות',
	mapItems: ' ישויות מפה',
	status: ' סטטוס',
};
export const textInPopUpGroupingRecordes = [
	{
		text: ' במיקוד',
		action: 'recordsInFillter',
	},
	{
		text: ' מחוץ למיקוד',
		action: 'allRecords',
	},
];
export const textInPopUpGroupingMapItems = [
	{
		text: 'נקודות עניין',
		action: 'pointOfInterest',
	},
	{
		text: 'תחנות',
		action: 'station',
	},
	{
		text: 'רכבים',
		action: 'cars',
	},
	{
		text: 'עומסי תנועה',
		action: 'traffic',
	},
];
export const textInPopUpGroupingStatus = [
    {
		text: 'כעת',
		action: 'active',
	},
    {
		text: 'צפוי ',
		action: 'expected',
	},
    {
		text: ' הסתיים ',
		action: 'finish',
	},
]
export const Text = {
    missing_driver_name : "MISSING DRIVER NAME",
    welcome:"ברוך הבא",
    records:"רשומות",
    inFocus:"במיקוד",
    outOfFocus:"מחוץ למיקוד",
    allRecords:"לא במיקוד",
    recordsInFilter:" במיקוד",
    noActiveRecords:"אין נסיעות פעילות",
    noRecordsInFocus:"אין רשומות במיקוד",
    driver:"נהג",
    car_number:"מספר רכב",
    car_type: "סוג רכב",
    client:"לקוח",
    escorted:"מלווה",
    message:"הערה",
    active: "נסיעה פעילה",
    currentTrip:"נסיעה נוכחית",
    expected:"נסיעה צפויה",
    finish:"נסיעה הסתיימה",
    next_trip : "הנסיעה הבאה",
    notActive: "נסיעה לא פעילה",
    noAssociatedTrips:"אין נסיעות משויכות",
    destination:"יעד סופי",
    start_point:"מוצא",
    inPractice:"בפועל",
    planned:"מתוכנן",
    scopes:"היקפים",
    logout:"התנתק",
    noStationsFound:"לנסיעה זו אין תחנות",
    setCurrentLeg:"קבע לג נוכחי",
    missing_status:"סטטוס חסר",
    noColor:"ללא",
    Pink: "ורוד",
    Torckiz:'תורכיז',
    Green:"ירוק",
    Yellow:"צהוב",
    Blue:"כחול",
    error_trip_details_not_found:"סליחה, לא מצאנו את פרטי הנסיעה",
    requirements:"דרישות",
    total:"סה\"כ",
    staffing_requirements:"דרישות לאיוש",
    undefinedStationName:"שם תחנה לא מזוהה",
    no_driver_staffed:"לא אויש נהג",
    no_car_staffed:"לא אויש רכב",
    resources:'משאבים',
    suitable:"מתאים",
    available:"פנוי",
    please_select_requirement:'בחר דרישה אחת או יותר',
    to_show_scedule:'להצגת לו״ז ומשאבים מתאימים',
    missing_start_time:"missing start time",
    missing_end_time:"missing end time",
    MISSING_CLIENT_NAME:"MISSING CLIENT NAME",
    MISSING_CAR_TYPE:"MISSING CAR TYPE",
    MISSING_ESCORT_NAME:"MISSING ESCORT NAME",
    MISSING_Line_DESCRIPTION:"MISSING LINE DESCRIPTION",
    textInPopUp:{
      centerMap: 'מרכוז מפה',
		colorMap: ' צביעה',
		connection: 'התקשרות',
    },
    translateHeaders: {
        nameOfTrip: 'שם נסיעה',
        startTime: 'התחלה',
        endTime: 'סיום',
        from: 'מוצא ',
        to: ' יעד',
        numOfPassengers:"מספר נוסעים",
        customerName:"שם לקוח",
        commens: 'הערות',
        car_type_id:'סוג רכב',
        publishedStatus: " ",
      },
      translateHeadersModal: {
        nameOfTrip: 'שם נסיעה',
        startTime: 'התחלה',
        endTime: 'סיום',
        from: 'מוצא ',
        to: ' יעד',
        numOfPassengers:"מספר נוסעים",
        customerName:"שם לקוח",
        commens: '',
      },
}
export default Text;
