export const extraFieldsOfTable = [
	{
		id: 'addIcon',
		Header: 'addIcon',
		accessor: 'addIcon',
		width: 150,
		column_width: 150,
		field_name: 'addIcon',
		label: 'addIcon',
		table_name: 'customers',
		is_active: true,
		column_order: 99,
		show_in_client: true,
	},
	{
		id: 'addIcon',
		Header: 'addIcon',
		accessor: 'addIcon',
		width: 150,
		column_width: 150,
		field_name: 'addIcon',
		label: 'addIcon',
		table_name: 'vehicles',
		is_active: true,
		column_order: 99,
		show_in_client: true,
	},
	{
		id: 'addIcon',
		Header: 'addIcon',
		accessor: 'addIcon',
		width: 150,
		column_width: 150,
		field_name: 'addIcon',
		label: 'addIcon',
		table_name: 'orders',
		is_active: true,
		column_order: 99,
		show_in_client: true,
	},
	{
		id: 'addIcon',
		Header: 'addIcon',
		accessor: 'addIcon',
		width: 150,
		column_width: 150,
		field_name: 'addIcon',
		label: 'addIcon',
		table_name: 'zones',
		is_active: true,
		column_order: 99,
		show_in_client: true,
	},

	{
		id: 'addIcon',
		Header: 'addIcon',
		accessor: 'addIcon',
		width: 150,
		column_width: 150,
		field_name: 'addIcon',
		label: 'addIcon',
		table_name: 'drivers',
		is_active: true,
		column_order: 99,
		show_in_client: true,
	},
	{
		id: 'addIcon',
		Header: 'addIcon',
		accessor: 'addIcon',
		width: 150,
		column_width: 150,
		field_name: 'addIcon',
		label: 'addIcon',
		table_name: 'permissions',
		is_active: true,
		column_order: 99,
		show_in_client: true,
	},
	{
		id: 'addIcon',
		Header: 'addIcon',
		accessor: 'addIcon',
		width: 150,
		column_width: 150,
		field_name: 'addIcon',
		label: 'addIcon',
		table_name: 'users',
		is_active: true,
		column_order: 99,
		show_in_client: true,
	},
	{
		id: 'addIcon',
		Header: 'addIcon',
		accessor: 'addIcon',
		width: 150,
		column_width: 150,
		field_name: 'addIcon',
		label: 'addIcon',
		table_name: 'contracts',
		is_active: true,
		column_order: 99,
		show_in_client: true,
	},
	{
		id: 'addIcon',
		Header: 'addIcon',
		accessor: 'addIcon',
		width: 150,
		column_width: 150,
		field_name: 'addIcon',
		label: 'addIcon',
		table_name: 'all_stations',
		is_active: true,
		column_order: 99,
		show_in_client: true,
	},
	{
		id: 'addIcon',
		Header: 'addIcon',
		accessor: 'addIcon',
		width: 150,
		column_width: 150,
		field_name: 'addIcon',
		label: 'addIcon',
		table_name: 'drivers_safty',
		is_active: true,
		column_order: 99,
		show_in_client: true,
	},
	// {
	// 	id: 'pricesListInContract',
	// 	Header: 'pricesListInContract',
	// 	accessor: 'pricesListInContract',
	// 	width: 150,
	// 	column_width: 150,
	// 	field_name: 'pricesListInContract',
	// 	label: 'pricesListInContract',
	// 	table_name: 'contracts',
	// 	is_active: true,
	// 	column_order: 99,
	// 	show_in_client: true,
	// },
	
];
